name: MirrorUpstream
on:
  schedule:
    - cron: '* * * * *'
jobs:
  MirrorUpstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 
        run: |
          git checkout upstream
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream https://github.com/pytorch/pytorch
          git fetch upstream master
          git rebase upstream/master 
          git push
